version: '3.7'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - users
      - posts
      - comments
      - query
      - moderation
      - votes
      - deadline
      - group
      - notifications
      - eventbus
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/auth?directConnection=true&authSource=admin

  users:
    build: ./users
    ports:
      - "4001:4001"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/users?directConnection=true&authSource=admin

  posts:
    build: ./posts
    ports:
      - "4002:4002"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/posts?directConnection=true&authSource=admin

  comments:
    build: ./comments
    ports:
      - "4003:4003"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/comments?directConnection=true&authSource=admin

  query:
    build: ./query
    ports:
      - "4004:4004"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/query?directConnection=true&authSource=admin

  moderation:
    build: ./moderation
    # ports:
    #   - "4005:4005"

  votes:
    build: ./votes
    ports:
      - "4006:4006"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/votes?directConnection=true&authSource=admin

  deadline:
    build: ./deadline
    ports:
      - "4007:4007"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/deadline?directConnection=true&authSource=admin

  group:
    build: ./group
    ports:
      - "4008:4008"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/group?directConnection=true&authSource=admin

  notifications:
    build: ./notifications
    # ports:
    #   - "4009:4009"

  eventbus:
    build: ./eventbus
    # ports:
    #   - "4010:4010"
  
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: