version: '3.7'
services:
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/auth?directConnection=true&authSource=admin

  users:
    build: ./users
    ports:
      - "4001:4001"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/users?directConnection=true&authSource=admin

  deadline:
    build: ./deadline
    ports:
      - "4007:4007"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/deadline?directConnection=true&authSource=admin

  votes:
    build: ./votes
    ports:
      - "4006:4006"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/votes?directConnection=true&authSource=admin

  group:
    build: ./group
    ports:
      - "4008:4008"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/group?directConnection=true&authSource=admin
  
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: